// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

// Gracefully handle missing environment variables
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.error('Missing Supabase environment variables. Please set up your .env file.');
  // Create a placeholder client that will show errors in the UI instead of crashing
  const errorMessage = !SUPABASE_URL 
    ? 'Missing VITE_SUPABASE_URL environment variable'
    : 'Missing VITE_SUPABASE_ANON_KEY environment variable';
  
  throw new Error(
    `${errorMessage}. Please copy .env.example to .env and set your Supabase credentials.`
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
