// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || 'https://xhzgistgvcbmcfczcrib.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhoemdpc3RndmNibWNmY3pjcmliIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3OTcxNDgsImV4cCI6MjA2NjM3MzE0OH0.xUizmSWO6Ri1b9I6IdMr1-mbu6v2YaSfKY2gcjV0Ow0';

// Validate required configuration
if (!SUPABASE_URL) {
  throw new Error('Supabase URL is required');
}

if (!SUPABASE_PUBLISHABLE_KEY) {
  throw new Error('Supabase anonymous key is required');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
